# Generated by Django 5.2.3 on 2025-08-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hall_api.officemaster'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin')], default='ADMIN', max_length=50, null=True),
        ),
    ]
