# Generated by Django 5.2.3 on 2025-08-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0002_alter_adminuser_office_alter_adminuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallmaster',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
