# Generated by Django 5.2.1 on 2025-08-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0003_hallmaster_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='remarks',
            new_name='description',
        ),
        migrations.AddField(
            model_name='booking',
            name='it_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='shift',
            field=models.CharField(choices=[('Day', 'Day'), ('Mid', 'Mid'), ('Night', 'Night')], default='Day', max_length=10),
        ),
    ]
