# Generated by Django 5.2.5 on 2025-08-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0005_hallmaster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(default='meeting', on_delete=django.db.models.deletion.CASCADE, to='hall_api.sessionmaster'),
        ),
    ]
