# Generated by Django 5.2.1 on 2025-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0006_alter_booking_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallmaster',
            name='is_freeze',
            field=models.BooleanField(default=False),
        ),
    ]
