# Generated by Django 5.2.1 on 2025-08-30 04:58

from django.db import migrations

def populate_entities(apps, schema_editor):
    Entity = apps.get_model('hall_api', 'Entity')
    entities_data = [
        {'entity_code': 'VDINC', 'entity_name': 'VDART Inc.', 'location': 'ATL, GA, USA'},
        {'entity_code': 'VDPL', 'entity_name': 'VDart Technologies Pvt. Ltd.', 'location': 'TRY, TN, IN'},
        {'entity_code': 'VDSS', 'entity_name': 'VDart Software Services', 'location': 'TRY, TN, IN'},
        {'entity_code': 'VDD', 'entity_name': 'VDart Digital Pvt. Ltd.', 'location': 'TRY, TN, IN'},
    ]
    for data in entities_data:
        Entity.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0007_hallmaster_is_freeze'),
    ]

    operations = [
        migrations.RunPython(populate_entities),
    ]
