# Generated by Django 5.2.3 on 2025-09-01 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0008_populate_entity_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallmaster',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hall_api.officemaster'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hall_api.hallmaster'),
        ),
        migrations.AlterField(
            model_name='sessionmaster',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hall_api.hallmaster'),
        ),
    ]
