# Generated by Django 5.2.1 on 2025-09-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0009_alter_hallmaster_office_alter_infrastructure_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('HR', 'Human Resources'), ('CAFFETERIA', 'Cafeteria'), ('IT_SUPPORT', 'IT Support')], default='ADMIN', max_length=50, null=True),
        ),
    ]
