# Generated by Django 5.2.3 on 2025-09-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0011_alter_adminuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallmaster',
            name='extension_power_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hallmaster',
            name='mic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hallmaster',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hallmaster',
            name='speaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hallmaster',
            name='stationaries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hallmaster',
            name='whiteboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hallmaster',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
