# Generated by Django 5.2.3 on 2025-09-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0012_hallmaster_extension_power_box_hallmaster_mic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallmaster',
            old_name='monitor',
            new_name='chairs_tables',
        ),
        migrations.AddField(
            model_name='hallmaster',
            name='tv',
            field=models.BooleanField(default=False),
        ),
    ]
