# Generated by Django 5.2.1 on 2025-09-03 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0012_hallmaster_extension_power_box_hallmaster_mic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hall_api.hallmaster')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_api.officemaster')),
            ],
            options={
                'unique_together': {('office', 'hall', 'blocked_date')},
            },
        ),
    ]
