# Generated by Django 5.2.1 on 2025-09-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0013_blockeddate'),
        ('hall_api', '0013_rename_monitor_hallmaster_chairs_tables_and_more'),
    ]

    operations = [
    ]
