# Generated by Django 5.2.1 on 2025-09-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_api', '0015_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallmaster',
            name='category',
            field=models.CharField(choices=[('CABIN', 'Cabin'), ('ROOM', 'Room'), ('HALL', 'Hall'), ('FLOOR', 'Floor'), ('OPEN', 'Open'), ('CSUITE', 'CSuite')], default='HALL', max_length=50),
        ),
    ]
